<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de finanças </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home">Gerenciador pessoal de gastos</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav justify-content-center">
            <li class='nav-item'>
                <a href="<?=HOME?>">Home</a>
            </li>
            <li class='nav-item'>
                <a href="<?=HOME?>/myexpenses">Despesas</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <?php if(\Code\Session\Session::has('user')): ?>
              <li class='nav-item'>
                <a href="<?=HOME?>/auth/logout">Sair</a>
              </li>
            <?php else: ?>
              <li class='nav-item'>
                <a href="<?=HOME?>/auth/login">Entrar</a>
            </li>
            <?php endif;?>
          </ul>
        </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>