<?php if(\Code\Session\Session::has("success")): ?>
    <div class="alert alert-success text-center">
        <?=\Code\Session\Flash::get("success");?>
    </div>
<?php endif;?>

<?php if(\Code\Session\Session::has("warning")): ?>
    <div class="alert alert-warning text-center">
        <?=\Code\Session\Flash::get('warning');?>
    </div>
<?php endif;?>

<?php if(\Code\Session\Session::has("danger")): ?>
    <div class="alert alert-danger text-center">
        <?=\Code\Session\Flash::get("danger");?>
    </div>
<?php endif;?>