<?php require VIEWS_PATH . 'includes/header.phtml';?>

<div class="container">
    <div class="col-md-12">
        <h1>Cadastrar nova despesa:</h1>
        <hr>
    </div>
    <div class="col-md-12">
        <form action="<?=HOME;?>/myexpenses/new" method="POST">
            <div class="form-group">
                <label for="value">Valor gasto:</label>
                <input type="text" class="form-control" name="value" placeholder="Valor gasto...">
            </div>
            <div class="form-group">
                <label for="category">Categoria:</label>
                <select name="categories_id" id="" class="form-control">
                    <?php foreach($this->categories as $category):?> 
                        <option value="<?=$category['id']?>"><?=$category['name']?></option>
                    <?php endforeach; ?>
                </select> 
            </div>
            <div class="form-group">
                <label for="description">Descrição:</label>
                <textarea name="description" id="" cols="15" rows="5" class="form-control" placeholder="Descreva sua despesa..."></textarea>
            </div>            
            <button class="btn btn-success btn-lg pull-right" >Salvar Despesa</button>
        </form>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml';?>