<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
    <div class="jumbotron">
        <h1>Gerenciador de gastos pessoal</h1>
        <p>
            3º projeto criado na maratona de PHP OO no cursinho da code experts.
        </p>
        <hr>
        <p>
            <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais... &raquo;</a>
        </p>
    </div>
    <div class="col-md-12">
        
    </div>
</div> 
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
    
